CREATE TABLE test_banner (
     id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     code VARCHAR2(255) UNIQUE,
     name VARCHAR2(255),
     picture VARCHAR2(255),
     bank_id VARCHAR2(255),
     main_banner NUMBER,
     icon VARCHAR2(255),
     text CLOB,  -- Use CLOB for large text in Oracle
     url VARCHAR2(255),
     url_text VARCHAR2(255),
     priority NUMBER,
     color VARCHAR2(255),
     available NUMBER(1),  -- Use NUMBER(1) for boolean values (0 or 1)
     platform VARCHAR2(255),
     CONSTRAINT fk_main_banner FOREIGN KEY (main_banner) REFERENCES test_banner(id)
);