-- Create the stories table
CREATE TABLE stories (
                         id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         bank_id VARCHAR2(255),
                         platform VARCHAR2(255),
                         font_size VARCHAR2(255),
                         preview_title VARCHAR2(255),
                         preview_title_color VARCHAR2(255),
                         preview_url VARCHAR2(255),
                         preview_gradient VARCHAR2(255),
                         approved VARCHAR2(15)
);

-- Create the frames table
CREATE TABLE frames (
    id RAW(16) PRIMARY KEY,  -- Oracle uses RAW data type for UUIDs
    story_id NUMBER,
    title VARCHAR2(255),
    text CLOB,  -- Use CLOB for text data in Oracle
    text_color VARCHAR2(255),
    picture_url VARCHAR2(255),
    visible_button_or_none VARCHAR2(255),
    button_text VARCHAR2(255),
    button_text_color VARCHAR2(255),
    button_background_color VARCHAR2(255),
    button_url VARCHAR2(255),
    gradient VARCHAR2(255),
    approved NUMBER(1),  -- Use NUMBER(1) for boolean values (0 or 1)
    CONSTRAINT fk_story FOREIGN KEY (story_id) REFERENCES stories(id)
);

-- Create the test_banner table
CREATE TABLE test_banner (
         id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
         code VARCHAR2(255) UNIQUE,
         name VARCHAR2(255),
         picture VARCHAR2(255),
         bank_id VARCHAR2(255),
         main_banner NUMBER,
         icon VARCHAR2(255),
         text CLOB,  -- Use CLOB for text data in Oracle
         url VARCHAR2(255),
         url_text VARCHAR2(255),
         priority NUMBER,
         color VARCHAR2(255),
         available NUMBER(1),  -- Use NUMBER(1) for boolean values (0 or 1)
         platform VARCHAR2(255),
         CONSTRAINT fk_main_banner FOREIGN KEY (main_banner) REFERENCES test_banner(id)
);
