CREATE TABLE history (
     id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     component_type VARCHAR2(30),
     operation_type VARCHAR2(30),
     bank VARCHAR2(30),
     platform VARCHAR2(30),
     status VARCHAR2(30),
     component_id NUMBER,
     time DATE,
     user_name VARCHAR2(255),
     CONSTRAINT fk_component FOREIGN KEY (component_id) REFERENCES stories(id)
);