version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres:13.3
    environment:
      POSTGRES_DB: "content_maker"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5433:5432"
  backend:
    build: 'backend/docker'
    container_name: static-content-backend
    ports:
      - '8080:8080'
    environment:
      - SPRING.PROFILES.ACTIVE=default
    depends_on:
      postgres:
        condition: service_healthy
  frontend:
    build: 'frontend/'
    container_name: static-content-frontend
    ports:
      - '3232:80'
    links:
      - backend
