version: '3'
services:
  backend:
    build:
      context: './backend'
      dockerfile: 'docker/Dockerfile'
    container_name: static-content-backend
    ports:
      - '8080:8080'
    environment:
      - SPRING_PROFILES_ACTIVE=default
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin_password
    ports:
      - "8484:8080"
    command:
      - start-dev
  frontend:
    build: 'frontend/'
    container_name: static-content-frontend
    ports:
      - '3232:80'
    links:
      - backend
