# curl -X POST http://localhost:8081/realms/content-maker/protocol/openid-connect/token 
#     -H "Content-Type: application/x-www-form-urlencoded" 
#     -d "client_id=maker&client_secret=dM0n3JQteH7Yhg4WN1Z4sCGAOfmFdIEk&username=admin&password=password&grant_type=password"
POST http://localhost:8081/realms/content-maker/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id = maker &
client_secret = ********** &
username = admin &
password = password &
grant_type = password

###

