title:
  text:
    validator:
      titleMaxLenForOneString: 17
      textMaxLenForOneString: 245
      textMaxStringCountForOneString: 7

      titleMaxLenForTwoString: 34
      textMaxLenForTwoString: 210
      textMaxStringCountForTwoString: 6

      titleMaxLenForThreeString: 51
      textMaxLenForThreeString: 140
      textMaxStringCountForThreeString: 4

preview:
  title:
    validator:
      titleMaxStringCount: 2

keycloak:
  realm: content-maker
  resource: maker
  auth-server-url: http://localhost:8081/auth
  use-resource-role-mappings: true
  principal-attribute: preferred_username


files:
  save:
    directory:
      filesSaveDirectory: "/content-maker/backend/src/main/resources/site/share/htdoc/_files/skins/mobws_story/"

spring:
  flyway:
    enabled: true
    locations:
      - db.migration
    validate-on-migrate: true
    baseline-on-migrate: true

  security:
    oauth2:
      resource server:
        jwt:
          issuer-uri: http://localhost:8081/realms/content-maker
      client:
        registration:
          keycloak:
            client-id: maker
            client-secret: "**********"
    user:
      name: admin
      password: password
  jpa:
    hibernate:
      ddl-auto: none  # Avoid auto schema creation if using Flyway
    database-platform: org.hibernate.dialect.Oracle12cDialect  # Use appropriate dialect
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@//localhost:1521/ORCLCDB
    username: system
    password: Oracle_123
    initialization-mode: always
    properties:
      user: system
      password: Oracle_123
      oracle.jdbc.OracleConnection.DEFAULTNAMESPACE: SYSDBA

  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
server:
  tomcat:
    max-http-form-post-size: 10485760

feature-flags:
  admin: true
  components:
    stories: true
    banners: false
#logging:
#  level:
#    org:
#      springframework:
#        security: DEBUG