title:
  text:
    validator:
      titleMaxLenForOneString: 17
      textMaxLenForOneString: 245
      textMaxStringCountForOneString: 7

      titleMaxLenForTwoString: 34
      textMaxLenForTwoString: 210
      textMaxStringCountForTwoString: 6

      titleMaxLenForThreeString: 51
      textMaxLenForThreeString: 140
      textMaxStringCountForThreeString: 4

preview:
  title:
    validator:
      titleMaxStringCount: 2

keycloak:
  realm: content-maker
  resource: maker
  auth-server-url: http://localhost:8080/auth
  use-resource-role-mappings: true
  principal-attribute: preferred_username


files:
  save:
    directory:
      filesSaveDirectory: "/content-maker/backend/src/main/resources/site/share/htdoc/_files/skins/mobws_story/"

spring:
#  mvc:
#    static-path-pattern: /content/**
#
#  web:
#    resources:
#      static-locations: /content/**

  flyway:
    enabled: true
    locations:
      - db.migration
    validate-on-migrate: true
    baseline-on-migrate: true

  security:
    oauth2:
      resource server:
        jwt:
          issuer-uri: http://localhost:8080/realms/content-maker
      client:
        registration:
          keycloak:
            client-id: maker
            client-secret: "**********"
    user:
      name: admin
      password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:1542/content_maker
    username: admin
    password: password

  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
server:
  tomcat:
    max-http-form-post-size:  10485760
  port: 8081

feature-flags:
  components:
    stories: true
    show_story: true
    banners: true
    admin_panel: true

file_path_to_save:
  stories: "src/main/resources/static/site/share/htdoc/_files/skins/mobws_story/"
  banners: "src/main/resources/static/site/share/htdoc/_files/skins/mobws_banners/"
#logging:
#  level:
#    org:
#      springframework:
#        security: DEBUG