title:
  text:
    validator:
      titleMaxLenForOneString: 17
      textMaxLenForOneString: 245
      textMaxStringCountForOneString: 7

      titleMaxLenForTwoString: 34
      textMaxLenForTwoString: 210
      textMaxStringCountForTwoString: 6

      titleMaxLenForThreeString: 51
      textMaxLenForThreeString: 140
      textMaxStringCountForThreeString: 4

preview:
  title:
    validator:
      titleMaxStringCount: 2

files:
  save:
    directory:
      filesSaveDirectory: "/content-maker/backend/src/main/resources/site/share/htdoc/_files/skins/mobws_story/"

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5430/content_maker
    username: admin
    password: password
    #    driverClassName: org.postgresql.Driver
  flyway:
    enabled: true
    locations:
      - db.migration
    validate:
      -off
      -migrate=false
  jpa:
   database-platform: org.hibernate.dialect.PostgreSQLDialect

  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
server:
  tomcat:
    max-http-form-post-size: 10485760